// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// FutureGenerator
// **************************************************************************

/// CODE GENERATED BY NOMOCODE
/// DO NOT EDIT

/// IMPORTING ORIGINAL SOURCE
import 'package:nobody/references.dart';

/// GENERATED EXTENSION
extension ExSpreadsheet on Future<Spreadsheet> {
  FutureOr<Iterable<Row>> rows(
    bool Function(Row) predicate,
  ) async {
    var Spreadsheet = await this;
    return Spreadsheet.rows(
      predicate,
    );
  }
}
