// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// FutureGenerator
// **************************************************************************

/// CODE GENERATED BY NOMOCODE
/// DO NOT EDIT

/// IMPORTING ORIGINAL SOURCE
import 'package:nobody/references.dart';

/// GENERATED EXTENSION
extension ExWorkbook on Future<Workbook> {
  Future<Spreadsheet> sheet(
    String name,
  ) async {
    var Workbook = await this;
    return Workbook.sheet(
      name,
    );
  }
}
