// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// FutureGenerator
// **************************************************************************

/// CODE GENERATED BY NOMOCODE
/// DO NOT EDIT

/// IMPORTING ORIGINAL SOURCE
import 'package:nobody/references.dart';

/// GENERATED EXTENSION
extension ExGraphQuery on Future<GraphQuery> {
  Future<GraphQuery> select(
    List<String> fields,
  ) async {
    var GraphQuery = await this;
    return GraphQuery.select(
      fields,
    );
  }

  Future<GraphQuery> top(
    int top,
  ) async {
    var GraphQuery = await this;
    return GraphQuery.top(
      top,
    );
  }

  Future<GraphQuery> orderBy(
    String orderBy,
  ) async {
    var GraphQuery = await this;
    return GraphQuery.orderBy(
      orderBy,
    );
  }

  Future<GraphQuery> filter(
    String filter,
  ) async {
    var GraphQuery = await this;
    return GraphQuery.filter(
      filter,
    );
  }

  Future<dynamic> get() async {
    var GraphQuery = await this;
    return GraphQuery.get();
  }

  Future<dynamic> post(
    Map<String, dynamic> data,
  ) async {
    var GraphQuery = await this;
    return GraphQuery.post(
      data,
    );
  }
}
