// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.3.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<int> myCustomFunc({required int a, required int b, dynamic hint}) =>
    RustLib.instance.api.myCustomFunc(a: a, b: b, hint: hint);

Future<void> show({required String name, dynamic hint}) =>
    RustLib.instance.api.show(name: name, hint: hint);

Future<List<String>> getFiles({dynamic hint}) =>
    RustLib.instance.api.getFiles(hint: hint);
