// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// FutureGenerator
// **************************************************************************

/// CODE GENERATED BY NOMOCODE
/// DO NOT EDIT

/// IMPORTING ORIGINAL SOURCE
import 'package:nobody/references.dart';

/// GENERATED EXTENSION
extension ExCell on Future<Cell> {}
