// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// FutureGenerator
// **************************************************************************

/// CODE GENERATED BY NOMOCODE
/// DO NOT EDIT

/// IMPORTING ORIGINAL SOURCE
import 'package:nobody/references.dart';

/// GENERATED EXTENSION
extension ExGraphServiceClient on Future<GraphServiceClient> {
  Future<GraphQuery> graph(
    String path,
  ) async {
    var GraphServiceClient = await this;
    return GraphServiceClient.graph(
      path,
    );
  }

  Future<MailQuery> read_mails() async {
    var GraphServiceClient = await this;
    return GraphServiceClient.read_mails();
  }

  Future<GraphQuery> find_files() async {
    var GraphServiceClient = await this;
    return GraphServiceClient.find_files();
  }
}
