// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// FutureGenerator
// **************************************************************************

/// CODE GENERATED BY NOMOCODE
/// DO NOT EDIT

/// IMPORTING ORIGINAL SOURCE
import 'package:nobody/references.dart';

/// GENERATED EXTENSION
extension ExGraphServiceClient on Future<GraphServiceClient> {
  Future<GraphServiceClient> about_me() async {
    var GraphServiceClient = await this;
    return GraphServiceClient.about_me();
  }

  Future<GraphQuery> graph(
    String path,
  ) async {
    var GraphServiceClient = await this;
    return GraphServiceClient.graph(
      path,
    );
  }

  Future<GraphQuery> mail() async {
    var GraphServiceClient = await this;
    return GraphServiceClient.read_mails();
  }

  Future<GraphQuery> files() async {
    var GraphServiceClient = await this;
    return GraphServiceClient.find_files();
  }
}
