// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// FutureGenerator
// **************************************************************************

/// CODE GENERATED BY nomo_code GENERATOR. DO NOT EDIT.

/// IMPORTING ORIGINAL SOURCE
import 'input.dart';

/// GENERATED EXTENSION
extension ExInput on Future<Input> {}
