// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// FutureGenerator
// **************************************************************************

/// CODE GENERATED BY nomo_code GENERATOR. DO NOT EDIT.

/// IMPORTING ORIGINAL SOURCE
import 'nobody.dart';

/// GENERATED EXTENSION
extension ExOnline on Future<Online> {
  Future<Online> visit(
    String url,
  ) async {
    var Online = await this;
    return Online.visit(
      url,
    );
  }

  Future<Online> type(
    String selector,
    String text,
  ) async {
    var Online = await this;
    return Online.type(
      selector,
      text,
    );
  }

  Future<Online> set(
    String selector,
    String text,
  ) async {
    var Online = await this;
    return Online.set(
      selector,
      text,
    );
  }

  Future<Online> click(
    String selector,
  ) async {
    var Online = await this;
    return Online.click(
      selector,
    );
  }

  Future<Online> waitFor(
    Future<bool> Function(Online) waitable,
  ) async {
    var Online = await this;
    return Online.waitFor(
      waitable,
    );
  }

  Future<Online> close() async {
    var Online = await this;
    return Online.close();
  }

  Future<Online> screenshot(
    String path,
  ) async {
    var Online = await this;
    return Online.screenshot(
      path,
    );
  }

  Future<Online> scrollToElement(
    String selector,
  ) async {
    var Online = await this;
    return Online.scrollToElement(
      selector,
    );
  }

  Future<Online> scrollBy(
    int x,
    int y,
  ) async {
    var Online = await this;
    return Online.scrollBy(
      x,
      y,
    );
  }

  Future<Online> switchToFrame(
    String selector,
  ) async {
    var Online = await this;
    return Online.switchToFrame(
      selector,
    );
  }
}
