// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// FutureGenerator
// **************************************************************************

/// CODE GENERATED BY NOMOCODE
/// DO NOT EDIT

/// IMPORTING ORIGINAL SOURCE
import 'package:nobody/references.dart';

/// GENERATED EXTENSION
extension ExOnline on Future<Online> {
  Future<Page> lastPage() async {
    var Online = await this;
    return Online.lastPage();
  }

  Future<Online> login(
    Authable authable,
  ) async {
    var Online = await this;
    return Online.login(
      authable,
    );
  }

  Future<Online> visit(
    String url,
  ) async {
    var Online = await this;
    return Online.visit(
      url,
    );
  }

  Future<Online> goto(
    AbstractUrl url,
  ) async {
    var Online = await this;
    return Online.goto(
      url,
    );
  }

  Future<Online> set(
    AbstractSelector selector,
    String text, {
    Duration? timeout = null,
    bool log = true,
    int index = 0,
  }) async {
    var Online = await this;
    return Online.set(
      selector,
      text,
      timeout: timeout,
      log: log,
      index: index,
    );
  }

  Future<Online> set_range(
    AbstractSelector selector,
    String from,
    String to, {
    Duration? timeout = null,
  }) async {
    var Online = await this;
    return Online.set_range(
      selector,
      from,
      to,
      timeout: timeout,
    );
  }

  Future<Online> type(
    String selector,
    String text,
  ) async {
    var Online = await this;
    return Online.type(
      selector,
      text,
    );
  }

  Future<Online> click(
    AbstractSelector selector,
  ) async {
    var Online = await this;
    return Online.click(
      selector,
    );
  }

  Future<Online> right_click(
    AbstractSelector selector,
  ) async {
    var Online = await this;
    return Online.right_click(
      selector,
    );
  }

  Future<Online> double_click(
    AbstractSelector selector,
  ) async {
    var Online = await this;
    return Online.double_click(
      selector,
    );
  }

  Future<Online> hover(
    AbstractSelector selector,
  ) async {
    var Online = await this;
    return Online.hover(
      selector,
    );
  }

  Future<Online> middle_click(
    AbstractSelector selector,
  ) async {
    var Online = await this;
    return Online.middle_click(
      selector,
    );
  }

  Future<Online> waitFor(
    AbstractSelector waitable, {
    Duration? timeout = null,
  }) async {
    var Online = await this;
    return Online.waitFor(
      waitable,
      timeout: timeout,
    );
  }

  Future<Online> wait(
    Future<bool> Function(Online) waitable,
  ) async {
    var Online = await this;
    return Online.wait(
      waitable,
    );
  }

  Future<Online> close() async {
    var Online = await this;
    return Online.close();
  }

  Future<Online> screenshot(
    String path,
  ) async {
    var Online = await this;
    return Online.screenshot(
      path,
    );
  }

  Future<Online> download(
    AbstractDownloadable downloadable,
    AbstractPath path,
  ) async {
    var Online = await this;
    return Online.download(
      downloadable,
      path,
    );
  }

  Future<Online> scrollToElement(
    AbstractSelector selector,
  ) async {
    var Online = await this;
    return Online.scrollToElement(
      selector,
    );
  }

  Future<Online> scrollBy(
    int x,
    int y,
  ) async {
    var Online = await this;
    return Online.scrollBy(
      x,
      y,
    );
  }

  Future<String?> get_value(
    AbstractSelector selector,
    String property,
  ) async {
    var Online = await this;
    return Online.get_value(
      selector,
      property,
    );
  }

  Future<dynamic> evaluate(
    String script,
  ) async {
    var Online = await this;
    return Online.evaluate(
      script,
    );
  }

  Future<List<Page>> pages() async {
    var Online = await this;
    return Online.pages();
  }

  Future<Page> newPage() async {
    var Online = await this;
    return Online.newPage();
  }

  Future<Page> get_page(
    int index,
  ) async {
    var Online = await this;
    return Online.get_page(
      index,
    );
  }

  Future<Online> close_page(
    int index,
  ) async {
    var Online = await this;
    return Online.close_page(
      index,
    );
  }

  Future<Online> close_all_pages() async {
    var Online = await this;
    return Online.close_all_pages();
  }

  Future<Online> close_all_other_pages() async {
    var Online = await this;
    return Online.close_all_other_pages();
  }

  Future<Online> list(
    AbstractSelector selector,
  ) async {
    var Online = await this;
    return Online.list(
      selector,
    );
  }

  Future<Online> send_hotkey(
    Key key, {
    List<Key>? modifiers = null,
  }) async {
    var Online = await this;
    return Online.send_hotkey(
      key,
      modifiers: modifiers,
    );
  }

  Future<Online> capture_download() async {
    var Online = await this;
    return Online.capture_download();
  }
}
