// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// FutureGenerator
// **************************************************************************

/// CODE GENERATED BY nomo_code GENERATOR. DO NOT EDIT.

/// IMPORTING ORIGINAL SOURCE
import 'sap.dart';

/// GENERATED EXTENSION
extension ExSapWebUi on Future<SapWebUi> {
  Future<SapWebUi> login(
    String username,
  ) async {
    var SapWebUi = await this;
    return SapWebUi.login(
      username,
    );
  }
}
